### ISSUE TITLE
Update referenced Kafka topic names to lower-case

### ISSUE THREAD

**Issue by osowski** [ibm-cloud-architecture/refarch-kc-ui#59]
Migrate all Kafka topic name references to lower-case, instead of camelCase.

This includes `bluewaterContainer`, `bluewaterProblem`, and `bluewaterShip` at a minimum for the `kc-ui` components. 

Other topics may be referenced directly in scripts and should be verified to be hyphenated lower-case and not camelCase.

**Comment by Darnele91** [comment]
A[ pull request](https://github.com/ibm-cloud-architecture/refarch-kc-ui/pull/63) has been created for this issue.

**Comment by osowski** [comment]
Closed via https://github.com/ibm-cloud-architecture/refarch-kc-ui/commit/85a14f4c7570ccea5aebeb4a00b8633f34cacbf1
