### ISSUE TITLE
Remove dead code for 'Customs Simulation' and 'Docker Simulation' from UI elements

### ISSUE THREAD

**Issue by osowski** [ibm-cloud-architecture/refarch-kc-ui#60]
In an effort to reduce complexity, parallel paths, and dead code, we will be removing elements from the originally planned UI that never came to fruition or paths have altered course drastically. 

For now, this should start as removal of the 'Customs Simulation' and 'Docker Simulation' buttons from the main UI homepage and any related code underneath those buttons/navigation elements.

![Screen Shot 2020-03-02 at 2 38 28 PM](https://user-images.githubusercontent.com/3410195/75715749-89cbbc80-5c93-11ea-8b3c-c1cf600c5757.png)

**Comment by Darnele91** [comment]
A pull request has been created for this issue. 
https://github.com/ibm-cloud-architecture/refarch-kc-ui/pull/61
